<?php
/**
 * This is a working Example. Copy it to your Project folder - it should work from the beginning
 */
namespace App;

use Phore\MicroApp\App;
use Phore\MicroApp\Auth\BasicUserProvider;
use Phore\MicroApp\Auth\HttpBasicAuthMech;

// We are using composer: Require the Autoloader generated by composer
require __DIR__ . "/../vendor/autoload.php";

// App is the main Phore Container/Dispatcher class
$app = new App();

// The most easiest way to authenticate is using HTTP Basic Authentication
$app->authManager->setAuthMech(new HttpBasicAuthMech());

// Define which users are available
$app->authManager->setUserProvider(
    new BasicUserProvider(
        [
            "admin:passwd:@admin:{name:'Hello Administrator'}",
            "admin2:passwd:@admin:{name:'Hello Nr2'}",
            "elfi:secret:@user:{name: 'Elfi'}"
        ],
        true    // <- Allow Plain-Text passwords - ALWAYS SET THIS TO false IN PRODUCTION ENVIRONMENTS
    )
);


// Allow only Authenticated Users to Access /admin/ Routes
$app->acl->addRule(aclRule()->route("/admin/*")->role("@admin")->ALLOW());

// Or if the request origins from localhost
$app->acl->addRule(aclRule()->route("/admin/*")->networks("127.0.0.1/8")->ALLOW());

// Deny other request (send Authentication Request) - DENY should be used to allow the user to authenticate
$app->acl->addRule(aclRule()->route("/admin/*")->DENY());



// Define the route
$app->router->get("/admin/", function () use ($app) {
    return $app->out("Hello Administror: UserName: {$app->authUser->userName} RealName: {$app->authUser->meta["name"]}");
});

$app->router->get("/", function () use ($app) {
    return $app->out("<a href='/admin/'>Go to admin</a>");
});


$app->serve();          // Run the application



